server:
  port: 31001
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:anyframe;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: anyframecloud
    password: anyframecloud
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: staging