endpoints:
  restart:
    enabled: true

management:
  contextPath: /admin

anyframe:
  cloud:
    auth:
      tokenUrl: http://localhost:8070/oauth/token?grant_type={grantType}
      checkTokenUrl: http://localhost:8070/oauth/check_token?token={access_token}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 3
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}