server:
  port: 28001
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:anyframe;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: anyframecloud
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
amqp:
  exchange:
    name: topic_cargos
  routingkey:
    cargoHandled: cargo.cargoHandled
    misdirected: cargo.misdirected
    delivered: cargo.delivered
    handlingEvent: cargo.handlingEvent
  queue-name:
    cargoHandled: cargoHandledQueue
    misdirected: misdirectedCargoQueue
    delivered: deliveredCargoQueue
    handlingEvent: handlingEventQueue
