server:
  port: 8889

spring:
  application:
    name: ConfigServer
  profiles:
     active: native
#  cloud:
#    config:
#      server:
#        git:
#          uri: http://70.121.244.190/gitnsam/anyframe/cargo-tracker-config.git
#          username: id
#          password: pw

